all:
  children:
    routers:
      hosts:
        router:
          ansible_host: 172.100.0.6
    switches:
      hosts:
        sw1:
          ansible_host: 172.100.0.5
        sw2:
          ansible_host: 172.100.0.3
    pcs:
      hosts:
        pc1:
          ansible_host: 172.100.0.2
        pc2:
          ansible_host: 172.100.0.4
