name: Deploy Network Lab


on:
  push:
    branches:
      - main


jobs:
  validate:
    name: Validate Ansible Playbooks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install ansible-lint and Collections
        run: |
          pip install ansible-lint
          ansible-galaxy collection install community.docker

      - name: Lint playbooks
        run: |
          ansible-lint ansible/playbooks/01-configurar-interfaces.yml
          ansible-lint ansible/playbooks/02-configurar-pcs.yml

  deploy:
    name: Deploy to Network Lab
    runs-on: [self-hosted, linux, network]
    needs: validate
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy network topology
        run: |
          cd /home/paris/Laboratorios/network-gitops-lab/containerlab
          sudo /usr/bin/containerlab destroy -t topology.yml --cleanup || true
          sudo /user/bin/containerlab deploy -t topology.yml
          echo "Esperando a que los demonios de FRR (Zebra) inicialicen..."
          sleep 15

      - name: Configure interfaces
        run: |
          cd /home/paris/Laboratorios/network-gitops-lab
          pip install --user ansible docker requests
          export PATH=$PATH:$HOME/.local/bin
          ansible-playbook -i ansible/inventory/hosts.yml ansible/playbooks/01-configurar-interfaces.yml

      - name: Configure PCs 
        run: |
          cd /home/paris/Laboratorios/network-gitops-lab
          export PATH=$PATH:$HOME/.local/bin
          ansible-playbook -i ansible/inventory/hosts.yml ansible/playbooks/02-configurar-pcs.yml

