name: Deploy Network Lab

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  validate:
    name: Validate Ansible Playbooks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install ansible-lint
        run: |
          pip install ansible-lint
          ansible-galaxy collection install community.docker

      - name: Lint playbooks
        run: |
          ansible-lint ansible/playbooks/01-configurar-interfaces.yml
          ansible-lint ansible/playbooks/02-configurar-pcs.yml

  deploy:
    name: Deploy to Network Lab
    runs-on: [self-hosted, Linux, network]
    needs: validate
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy network topology
        run: bash /home/paris/Laboratorios/scripts/deploy-topology.sh

      - name: Esperar inicializacion
        run: sleep 15

      - name: Configure interfaces
        run: |
          cd /home/paris/Laboratorios/network-gitops-lab
          ansible-playbook -i ansible/inventory/hosts.yml ansible/playbooks/01-configurar-interfaces.yml

      - name: Configure PCs
        run: |
          cd /home/paris/Laboratorios/network-gitops-lab
          ansible-playbook -i ansible/inventory/hosts.yml ansible/playbooks/02-configurar-pcs.yml
